name: pbl
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1 # Thêm dòng này
  shared_preferences: ^2.2.3

  # Networking
  dio: ^5.4.1

  # State Management
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5 # Hỗ trợ so sánh object trong Bloc rất tốt

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Đã cập nhật lên bản ổn định hơn cho SDK 3.10+

flutter:
  uses-material-design: true

  assets:
    - assets/images/